{
  "config": {
    "environments": [
      {
        "dev": {
          "phases": [
            {
              "duration": 10,
              "arrivalRate": 1
            }
          ]
        }
      }
    ]
  }
}
